# '''I / we certify that the code and data in this assignment were generated independently, using only the tools
# and resources defined in the course and that I/we did not receive any external help, coaching, or contributions
# during the production of this work.'''
---
# Environment
CUDA : False

# Training
epoch: 100000
timesteps: 250
batch_size: 1024
disc_factor: 0.99
buffer_size_adversary: 37500
buffer_size_agent: 112500
tau : 0.1

# Validation
epoch_val : 100

# Neural Network
architecture : "ddpg" #This can be PPO or DDPG
actor_hn: 256
critic_hn : 256
lr_actor : 0.001
lr_critic: 0.001
alpha: 0.1

# OU Noise
mu : 0.0
theta : 0.15
max_sigma: 0.3
min_sigma: 0.3
decay_steps: 50000

#Experince Replay
exp_alpha : 0.65

